version: '3'
networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24    

services:
  dummy-backend:
    build: ./tests/dummy-backend
    image: artofimagination/dummy-backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BACKEND}:${BACKEND_DOCKER}
    ports:
      - 8184:8184
    networks: 
      test-network:
        ipv4_address: 172.18.0.4
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        SERVER_PORT: ${FRONTEND_SERVER_PORT}
    image: artofimagination/polygnosics-frontend
    ports:
      - ${FRONTEND_SERVER_PORT}:${FRONTEND_SERVER_PORT}
    networks: 
      - test-network
    environment:
      SERVER_PORT: ${FRONTEND_SERVER_PORT}
    volumes:
      - ${BACKEND}:${BACKEND_DOCKER}
    depends_on:
      - dummy-backend