name: UI Test CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: UI Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r tests/requirements.txt
    - name: Lint with flake8
      run: |
        pip3 install flake8
        # Stop the build if there are flake8 issues
        flake8 . --count --show-source --statistics --exclude=temp
    - name: Install Chrome and Firefox
      run: |
        sudo apt install google-chrome-stable
        sudo apt-get install firefox
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Install chromedriver and geckodriver (Firefox Webdriver)
      run: |
        seleniumbase install chromedriver
        seleniumbase install geckodriver
    - name: Start test server
      run: cp tests/.env_functional_test .env && docker-compose --file docker-compose-test.yml up -d polygnosics
    - name: Run tests
      run: pytest -v tests/UI --soft-asserts
